# Generated by Django 5.2.7 on 2025-10-29 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("dtainicio", models.DateTimeField(auto_now_add=True)),
                ("dtaconclusao", models.DateTimeField(blank=True, null=True)),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Tarefa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("concluida", models.BooleanField(default=False)),
                ("dtainicio", models.DateTimeField(auto_now_add=True)),
                ("dtaconclusao", models.DateTimeField(blank=True, null=True)),
                ("prioridade", models.IntegerField()),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarefas",
                        to="projeto.projeto",
                    ),
                ),
            ],
        ),
    ]
